# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---
- name: Start of CI/CD pipeline
  hosts: netcicd
  gather_facts: false
  collections:
    - cisco.ios
    - cisco.iosxr
    - cisco.nxos
    - ansible.netcommon
          
  roles:
    - topology

- name: Aggregate test results
  hosts: localhost
  tasks:
    - name: Check if tests are done
      find:
        path: roles/topology/files/reports
        pattern: "*.xml"
      register: topology_test_result

    - debug: 
        msg: "No reports found"
      when: topology_test_result.matched == 0

    - name: "Publishing reports" 
      local_action: shell rebot --output topology_unittest.xml --log topology_unittest_log.html --report topology_unittest_report.html --outputdir ../ *.xml 
      args:
        chdir: roles/topology/files/reports
      when: topology_test_result.matched != 0 
...
