# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---
####################################################################
# Classic IOS specific commands                                    #
####################################################################

- name: Validate bundles
  local_action: shell robot -T --variable NODE:{{ inventory_hostname }} --variable LANG:{{ ansible_network_os }} --variable STAGE:{{ stage }} --name Hostname_test_{{ inventory_hostname }} --outputdir ../reports bundles.robot
  args:
    chdir: roles/topology/files/tests/
  register: "{{ ansible_network_os }}_bundles_output"
  listen: "{{ ansible_network_os }}_bundles"
  
- name: Print testresults
  debug: 
    var: "{{ ansible_network_os }}_bundles_output.stdout_lines"
  failed_when: "'Assertion Failed' in iosxr_bundles_output.stdout"
  listen: "{{ ansible_network_os }}_bundles"

####################################################################
# IOSXE specific commands                                          #
####################################################################

# IOSXE is managed through classic IOS or netconf

####################################################################
# IOSXR specific commands                                          #
####################################################################

- name: Validate bundles
  local_action: shell robot -T --variable NODE:{{ inventory_hostname }} --variable LANG:{{ ansible_network_os }} --variable STAGE:{{ stage }} --name Hostname_test_{{ inventory_hostname }} --outputdir ../reports bundles.robot
  args:
    chdir: roles/topology/files/tests/
  register: "{{ ansible_network_os }}_bundles_output"
  listen: "{{ ansible_network_os }}_bundles"
  
- name: Print testresults
  debug: 
    var: "{{ ansible_network_os }}_bundles_output.stdout_lines"
  failed_when: "'Assertion Failed' in iosxr_bundles_output.stdout"
  listen: "{{ ansible_network_os }}_bundles"

####################################################################
# NXOS specific commands                                           #
####################################################################

- name: Validate bundles
  local_action: shell robot -T --variable NODE:{{ inventory_hostname }} --variable LANG:{{ ansible_network_os }} --variable STAGE:{{ stage }} --name Hostname_test_{{ inventory_hostname }} --outputdir ../reports bundles.robot
  args:
    chdir: roles/topology/files/tests/
  register: "{{ ansible_network_os }}_bundles_output"
  listen: "{{ ansible_network_os }}_bundles"
  
- name: Print testresults
  debug: 
    var: "{{ ansible_network_os }}_bundles_output.stdout_lines"
  failed_when: "'Assertion Failed' in iosxr_bundles_output.stdout"
  listen: "{{ ansible_network_os }}_bundles"

...