# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---
- name: Validate bundle
  local_action: shell robot -T --variable NODE:{{ inventory_hostname }} --variable LANG:{{ ansible_network_os }} --variable STAGE:{{ stage }} --name Hostname_test_{{ inventory_hostname }} --outputdir ../reports bundles.robot
  args:
    chdir: roles/topology/files/tests/
  register: test_output
  listen: iosxr_bundles
  
- name: Print testresults
  debug: 
    var: test_output.stdout_lines
  failed_when: "'Assertion Failed' in test_output.stdout"
  listen: iosxr_bundles
...