# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---
####################################################################
# Classic IOS specific commands                                    #
####################################################################

- name: Validate GE interfaces
  local_action: shell robot -T --variable NODE:{{ inventory_hostname }} --variable LANG:{{ ansible_network_os }} --variable STAGE:{{ stage }} --name Hostname_test_{{ inventory_hostname }} --outputdir ../reports GeInterfacces.robot
  args:
    chdir: roles/topology/files/tests/
  register: test_output
  listen: ios_GeInterfaces
  
- name: Print testresults
  debug: 
    var: test_output.stdout_lines
  failed_when: "'Assertion Failed' in test_output.stdout"
  listen: ios_GeInterfaces

####################################################################
# IOSXE specific commands                                          #
####################################################################

# IOSXE is managed through classic IOS or netconf

####################################################################
# IOSXR specific commands                                          #
####################################################################

####################################################################
# NXOS specific commands                                           #
####################################################################

...