# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
  
- name: Add ssh user key for user to IOS
  vars:
    ansible_connection: network_cli
  cisco.ios.ios_config:
    lines:
      - key-hash ssh-rsa "{{ np_pubkey.stdout_lines[0] }}"
    parents:
      - ip ssh pubkey-chain
      - username netcicd-pipeline
