# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
  
- name: enable netconf
  vars:
    ansible_connection: network_cli
  cisco.ios.ios_config:
    lines:
      - netconf-yang
  register: netconf_enabled
  
- name: Wait until netconf has started
  wait_for: timeout=90
  delegate_to: localhost
  when: netconf_enabled is changed

