# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---
- name: Prepare IOSxr routers for SSH
  telnet:
    user: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    login_prompt: "Username: "
    prompts:
      - "[]#]"
    command:
      - crypto key gen rsa
      - "2048"
  
- name: Validate key existence on IOSXR
  telnet:
    user: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    login_prompt: "Username: "
    prompts:
      - "[>|#]"
    command:
      - sh crypto key my rsa

- name: Copy b64 pubkey to the IOSXR router
  local_action: shell sshpass -p {{ ansible_ssh_pass }} scp -q ~/.ssh/id_rsa_pub.b64 netcicd-pipeline@{{ ansible_host }}:/disk0:/id_rsa_pub.b64

- name: Import SSH key to IOSXR node
  vars:
    ansible_connection: network_cli
  cisco.iosxr.iosxr_command:
    commands:
      - crypto key import authentication rsa disk0:/id_rsa_pub.b64
      - show crypto key authentication rsa
  
- name: Disable telnet on IOSXR
  vars:
    ansible_connection: network_cli
  cisco.iosxr.iosxr_config:
    lines:
      - no telnet ipv4 server max-servers 10
...