# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---
- name: Enable ssh for IOS, IOSXE for user cisco
  import_tasks: ios.yml
  when: (("ios" in group_names) or ("iosxe" in group_names))
  
- name: Enable netconf on IOSXE
  import_tasks: iosxe.yml
  when: ("iosxe" in group_names)

- name: Enable ssh and netconf on IOSXR
  vars:
    ansible_connection: local
  import_tasks: iosxr.yml
  when: ("iosxr" in group_names)

- name: Enable ssh and netconf on NXOS
  import_tasks: nxos.yml
  when: ("nxos" in group_names)
...