# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---
- name: Get ssh user pubkey for user 
  local_action: shell ssh-keygen -E MD5 -lf ~/.ssh/id_rsa.pub | awk '{ print $2}' | cut -n -c 5- | sed 's/://g'
  register: np_pubkey

- name: Generate base64 ssh user pubkey for user 
  local_action: shell cut -d" " -f2 ~/.ssh/id_rsa.pub | base64 -d > ~/.ssh/id_rsa_pub.b64

- name: Enable ssh for IOS, IOSXE for user cisco
  import_tasks: ios.yml
  when: (("ios" in group_names) or ("iosxe" in group_names))
  
- name: Enable netconf on IOSXE
  import_tasks: iosxe.yml
  when: ("iosxe" in group_names)

- name: Enable ssh and netconf on IOSXR
  vars:
    ansible_connection: local
  import_tasks: iosxr.yml
  when: ("iosxr" in group_names)

- name: Enable ssh and netconf on NXOS
  import_tasks: nxos.yml
  when: ("nxos" in group_names)
...