# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---
- name: Copy pubkey to the router
  local_action: shell sshpass -p {{ ansible_ssh_pass }} scp -q ~/.ssh/id_rsa.pub netcicd-pipeline@{{ ansible_host }}:id_rsa.pub

- name: Import SSH key to nx-os node
  vars:
    ansible_connection: network_cli
  cisco.nxos.nxos_config:
    lines:
      - username netcicd-pipeline sshkey file bootflash:id_rsa.pub
      - show user-account
  
- name: Disable scp server
  vars:
    ansible_connection: network_cli
  cisco.nxos.nxos_config:
    lines:
      - no feature scp
...