# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---
owner: netcicd
domain: netcicd.example.com
ntp_key_id: 1
ntp_key: netcicd
timezone: CET
time_offset: 1
rescue: C!sco123
ansible_user: netcicd-pipeline
ansible_ssh_pass: C!sco123
ansible_connection_timeout: 30
...
