# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

####################################################################
# Classic IOS specific commands                                    #
####################################################################

####################################################################
# IOSXR CLI specific commands                                      #
####################################################################

####################################################################
# NXOS CLI specific commands                                       #
####################################################################

####################################################################
# Netconf specific commands for IOSXR                              #
####################################################################

- name: "Create ISIS keychain for IOSXR with Netconf"                                                       
  ansible.netcommon.netconf_config:                                                                                                                                    
    content: "{{ lookup('template', '{{ ansible_network_os }}_nc_isis_keychain.j2') }}"
  when: (ansible_connection is defined and ansible_connection == "netconf" and ansible_network_os == "iosxr" )                           
#  notify:                                                                                         
#    - iosxr_isis_keychain                                                                                    
   
####################################################################
# Kick off handlers                                                #
####################################################################
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers