# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---
- name: Validate exec banner
  local_action: shell robot -T --variable NODE:{{ inventory_hostname }} --variable LANG:{{ ansible_network_os }} --variable STAGE:{{ stage }} --name Banner_exec_test_{{ inventory_hostname }} --outputdir ../reports banner_exec.robot
  args:
    chdir: roles/box/files/tests/
  register: banner_output
  listen: exec_banner
  
- name: Validate login banner
  local_action: shell robot -T --variable NODE:{{ inventory_hostname }} --variable LANG:{{ ansible_network_os }} --variable STAGE:{{ stage }} --name Banner_login_test_{{ inventory_hostname }} --outputdir ../reports banner_login.robot
  args:
    chdir: roles/box/files/tests/
  register: banner_output
  listen: exec_banner
  
- name: Validate motd banner
  local_action: shell robot -T --variable NODE:{{ inventory_hostname }} --variable LANG:{{ ansible_network_os }} --variable STAGE:{{ stage }} --name Banner_motd_test_{{ inventory_hostname }} --outputdir ../reports banner_motd.robot
  args:
    chdir: roles/box/files/tests/
  register: banner_output
  listen: exec_banner
  
- name: Validate incoming banner
  local_action: shell robot -T --variable NODE:{{ inventory_hostname }} --variable LANG:{{ ansible_network_os }} --variable STAGE:{{ stage }} --name Banner_incoming_test_{{ inventory_hostname }} --outputdir ../reports banner_incoming.robot
  args:
    chdir: roles/box/files/tests/
  register: banner_output
  listen: exec_banner
  
- name: Print testresults
  debug: 
    var: test_output.stdout_lines
  failed_when: "'Assertion Failed' in test_output.stdout"
  listen: banners
...