# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

####################################################################
# Classic IOS specific commands                                    #
####################################################################

- name: "RADIUS based AAA"
  cisco.ios.ios_config:
    src: "ios_aaa.j2"
  when: (ansible_network_os is defined and ansible_network_os == "cisco.ios.ios" and ansible_connection is defined and ansible_connection == "ansible.netcommon.network_cli")
  
- name: "Add RADIUS servers"
  cisco.ios.ios_config:
    src: "ios_aaa_RADIUS_servers.j2"
  when: (ansible_network_os is defined and ansible_network_os == "cisco.ios.ios" and ansible_connection is defined and ansible_connection == "ansible.netcommon.network_cli")
  notify: 
    - ios_aaa
    
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

####################################################################
# IOSXR Netconf specific commands                                  #
####################################################################

- name: "RADIUS based AAA"
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ creds['username'] }}"
    password: "{{ creds['password'] }}"
    src: "{{ netconf }}_nc_aaa.j2"
  when: netconf is defined
  notify: 
    - aaa

- name: "Add RADIUS servers"
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ creds['username'] }}"
    password: "{{ creds['password'] }}"
    src: "{{ netconf }}_nc_aaa_RADIUS_servers.j2"
  when: netconf is defined
  notify: 
    - aaa

####################################################################
# Classic IOS specific commands                                    #
####################################################################

- name: "RADIUS based AAA"
  ios_config:
    provider: "{{ provider }}"
    authorize: yes
    src: "ios_aaa.j2"
  when:  (ansible_network_os is defined and ansible_network_os == "ios")
  
- name: "Add RADIUS servers"
  ios_config:
    provider: "{{ provider }}"
    authorize: yes
    src: "ios_aaa_RADIUS_servers.j2"
  when:  (ansible_network_os is defined and ansible_network_os == "ios")
    
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
