# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

####################################################################
# Classic IOS specific commands                                    #
####################################################################

- name: "IOS configure AUX port"
  ios_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_aux.j2"
  when: (ansible_network_os is defined and ansible_network_os == "cisco.ios.ios" and ansible_connection is defined and ansible_connection == "ansible.netcommon.network_cli")
#  notify: 
#    - console

####################################################################
# IOSXR specific commands                                          #
####################################################################

- name: "IOSXR configure console"
  iosxr_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_aux.j2"
  when: (ansible_network_os is defined and ansible_network_os == "iosxr" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - console

####################################################################
# NXOS specific commands                                           #
####################################################################

# No aux port on nxos

####################################################################
# Netconf specific commands                                        #
####################################################################

#no aux port on IOSXRv
    
####################################################################
# Kick off handlers for unit testing                               #
####################################################################
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers