# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

####################################################################
# Banners supported by generic Ansible module                      #
# Only IOS-type devices have a login banner, nxos does not         #
####################################################################

- name: "Set login banner non-nexus devices"
  net_banner:
    banner: login
    text: "{{ lookup('file', 'templates/banner_login.j2') }}"
    state: present
  when: (ansible_network_os is defined and ansible_network_os != "nxos")
#  notify: 
#    - banners

####################################################################
# Banners supported by generic Ansible module                      #
# nxos has exec banner                                             #
####################################################################

- name: "Set exec banner"
  net_banner:
    banner: exec
    text: "{{ lookup('file', 'templates/banner_exec.j2') }}"
    state: present
  when: (ansible_network_os is defined and ansible_network_os != "iosxr")
#  notify: 
#    - banners

####################################################################
# MOTD banner has Ansible net_module, regardless of network_os     #
####################################################################

- name: "Set motd banner"
  net_banner:
    banner: motd
    text: "{{ lookup('file', '../templates/banner_motd.j2') }}"
    state: present
#  notify: 
#    - banners

####################################################################
# Kick off handlers for unit testing                               #
####################################################################
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers