# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

####################################################################
# Classic IOS specific commands                                    #
####################################################################

- name: "Set login banner on IOS"
  cisco.ios.ios_banner:
    banner: login
    text: "{{ lookup('file', 'templates/banner_login.j2') }}"
    state: present
  when: "'ios' in group_names"
  notify: 
    - login_banner

- name: "Set exec banner on IOS"
  cisco.ios.ios_banner:
    banner: exec
    text: "{{ lookup('file', 'templates/banner_exec.j2') }}"
    state: present
  when: "'ios' in group_names"
  notify: 
    - exec_banner

- name: "Set motd banner on IOS"
  cisco.ios.ios_banner:
    banner: motd
    text: "{{ lookup('file', '../templates/banner_motd.j2') }}"
    state: present
  when: "'ios' in group_names"
  notify: 
    - motd_banner

####################################################################
# IOSXE specific commands                                          #
####################################################################

- name: "Set login banner on IOS"
  cisco.ios.ios_banner:
    banner: login
    text: "{{ lookup('file', 'templates/banner_login.j2') }}"
    state: present
  when: "'iosxe' in group_names"
  notify: 
    - login_banner

- name: "Set exec banner on IOS"
  cisco.ios.ios_banner:
    banner: exec
    text: "{{ lookup('file', 'templates/banner_exec.j2') }}"
    state: present
  when: "'iosxe' in group_names"
  notify: 
    - exec_banner

- name: "Set motd banner on IOS"
  cisco.ios.ios_banner:
    banner: motd
    text: "{{ lookup('file', '../templates/banner_motd.j2') }}"
    state: present
  when: "'iosxe' in group_names"
  notify: 
    - motd_banner

####################################################################
# IOSXR specific commands                                          #
####################################################################

- name: "Set login banner on IOS"
  cisco.iosxr.iosxr_banner:
    banner: login
    text: "{{ lookup('file', 'templates/banner_login.j2') }}"
    state: present
  when: "'iosxr' in group_names"
  notify: 
    - login_banner

- name: "Set exec banner on IOS"
  cisco.iosxr.iosxr_banner:
    banner: exec
    text: "{{ lookup('file', 'templates/banner_exec.j2') }}"
    state: present
  when: "'iosxr' in group_names"
  notify: 
    - exec_banner

- name: "Set motd banner on IOS"
  cisco.iosxr.iosxr_banner:
    banner: motd
    text: "{{ lookup('file', '../templates/banner_motd.j2') }}"
    state: present
  when: "'iosxr' in group_names"
  notify: 
    - motd_banner


####################################################################
# NXOS specific commands                                           #
####################################################################

- name: "Set exec banner on nxos"
  cisco.nxos.nxos_banner:
    banner: exec
    text: "{{ lookup('file', 'templates/banner_exec.j2') }}"
    state: present
  when: "'nxos' in group_names"
  notify: 
    - exec_banner

- name: "Set motd banner on IOS"
  cisco.nxos.nxos_banner:
    banner: motd
    text: "{{ lookup('file', '../templates/banner_motd.j2') }}"
    state: present
  when: "'nxos' in group_names"
  notify: 
    - motd_banner

####################################################################
# Kick off handlers for unit testing                               #
####################################################################
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers