# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

####################################################################
# Classic IOS specific commands                                    #
####################################################################

- name: "IOS configure console"
  ios_config:
    authorize: yes
    lines:
      - password {{ console_pass }}
      - authorization exec console
      - logging synchronous
      - login authentication console
      - stopbits 1
    parents: ['line con 0']
    when: (ansible_network_os is defined and ansible_network_os == "ios" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - console

####################################################################
# IOSXR specific commands                                          #
####################################################################

- name: "IOSXR configure console"
  iosxr_config:
    authorize: yes
    lines:
      - password {{ console_pass }}
      - authorization exec console
      - logging synchronous
      - login authentication console
      - stopbits 1
    parents: ['line con 0']
  when: (ansible_network_os is defined and ansible_network_os == "iosxr" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - console

####################################################################
# NXOS specific commands                                           #
####################################################################

- name: "NX-OS configure console"
  nxos_config:
    lines:
      - password {{ console_pass }}
      - authorization exec console
      - logging synchronous
      - login authentication console
      - stopbits 1
    parents: ['line con 0']
    save_when: modified
  when: (ansible_network_os is defined and ansible_network_os == "nxos" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - console

####################################################################
# Netconf specific commands                                        #
####################################################################

- name: "Netconf configure console"
  netconf_config:
    src: "{{ ansible_network_os }}_nc_console.j2"
  when: (ansible_connection is defined and ansible_connection == "netconf")
#  notify: 
#    - console
    
####################################################################
# Kick off handlers for unit testing                               #
####################################################################
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers