# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

####################################################################
# Classic IOS specific commands                                    #
####################################################################

- name: "IOS Disable unused services"
  cisco.ios.ios_config:
    src: "{{ ansible_network_os }}_cli_disable_services.j2"
  when: (ansible_network_os is defined and ansible_network_os == "ios" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - ios_hardening_disable_unused_services

- name: "IOS enable required services"
  cisco.ios.ios_config:
    src: "{{ ansible_network_os }}_cli_enable_services.j2"
  when: (ansible_network_os is defined and ansible_network_os == "ios" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - ios_hardening_required_services

- name: "IOS Disable source routing"
  cisco.ios.ios_config:
    src: "{{ ansible_network_os }}_cli_disable_source_routing.j2"
  when: (ansible_network_os is defined and ansible_network_os == "ios" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - ios_hardening_disable_source_routing

- name: "IOS Disable http/https servers"
  cisco.ios.ios_config:
    src: "{{ ansible_network_os }}_cli_disable_http.j2"
  when: (ansible_network_os is defined and ansible_network_os == "ios" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - ios_hardening_disable_webservers

- name: "IOS Disable CDP globally"
  cisco.ios.ios_config:
    src: "{{ ansible_network_os }}_cli_disable_cdp.j2"
  when: (ansible_network_os is defined and ansible_network_os == "ios" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - ios_hardening_disable_cdp

####################################################################
# IOSXE specific commands                                          #
####################################################################

# IOSXE is managed through classic IOS or netconf

####################################################################
# IOSXR specific commands                                          #
####################################################################

# IOSXR is managed through netconf

####################################################################
# NXOS specific commands                                           #
####################################################################

- name: "NXOS Disable unused services"
  cisco.nxos.nxos_config:
    src: "{{ ansible_network_os }}_cli_disable_services.j2"
  when: (ansible_network_os is defined and ansible_network_os == "nxos" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - nxos_hardening_disable_unused_services

- name: "NXOS Disable source routing"
  cisco.nxos.nxos_config:
    src: "{{ ansible_network_os }}_cli_disable_source_routing.j2"
  when: (ansible_network_os is defined and ansible_network_os == "nxos" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - nxos_hardening_disable_source_routing

- name: "NXOS Disable CDP globally"
  cisco.nxos.nxos_config:
    src: "{{ ansible_network_os }}_cli_disable_cdp.j2"
  when: (ansible_network_os is defined and ansible_network_os == "nxos" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - nxos_hardening_disable_cdp

####################################################################
# Netconf specific commands                                        #
####################################################################

- name: "NC Disable unused services"
  ansible.netcommon.netconf_config:
    content: "{{ lookup('template', '{{ ansible_network_os }}_nc_disable_services.j2') }}"
  when: (ansible_network_os is defined and ansible_network_os == "iosxr" and ansible_connection is defined and ansible_connection == "netconf")
#  notify: 
#    - hardening

#- name: "NC Disable source routing"
#  ansible.netcommon.netconf_config:
#    content: "{{ lookup('template', '../templates/{{ ansible_network_os }}_nc_disable_sourcerouting.j2') }}"
#  when: (ansible_network_os is defined and ansible_network_os == "iosxr" and ansible_connection is defined and ansible_connection == "netconf")
#  notify: 
#    - hardening

#- name: "NC Disable http/https servers"
#  ansible.netcommon.netconf_config:
#    content: "{{ lookup('template', '../templates/{{ ansible_network_os }}_nc_disable_http.j2') }}"
#  when: (ansible_network_os is defined and ansible_network_os == "iosxr" and ansible_connection is defined and ansible_connection == "netconf")
#  notify: 
#    - hardening

#- name: "NC Disable CDP globally"
#  ansible.netcommon.netconf_config:
#    content: "{{ lookup('template', '../templates/{{ ansible_network_os }}_nc_disable_cdp.j2') }}"
#  when: (ansible_network_os is defined and ansible_network_os == "iosxr" and ansible_connection is defined and ansible_connection == "netconf")
#  notify: 
#    - hardening

####################################################################
# Kick off handlers for unit testing                               #
####################################################################
    
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
