# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

####################################################################
# Classic IOS specific commands                                    #
####################################################################

- name: "IOS set hostname"
  cisco.ios.ios_config:
    src: "{{ ansible_network_os }}_cli_hostname.j2"
  when: (ansible_network_os is defined and ansible_network_os == "ios" and ansible_connection is defined and ansible_connection == "network_cli")
  notify: 
    - ios_hostname

####################################################################
# IOSXE specific commands                                          #
####################################################################

# IOSXE is managed through classic IOS or netconf

####################################################################
# IOSXR specific commands                                          #
####################################################################

# IOSXR is managed through netconf

####################################################################
# NXOS specific commands                                           #
####################################################################

- name: "NX-OS set hostname"
  cisco.nxos.nxos_config:
    src: "{{ ansible_network_os }}_cli_hostname.j2"
    save_when: modified
  when: (ansible_network_os is defined and ansible_network_os == "nxos" and ansible_connection is defined and ansible_connection == "network_cli")
  notify: 
    - nxos_hostname

####################################################################
# Netconf specific commands                                        #
####################################################################

- name: "Netconf set hostname"
  ansible.netcommon.netconf_config:
    content: "{{ ansible_network_os }}_nc_hostname.j2"
  when: (ansible_network_os is defined and ansible_network_os == "iosxr" and ansible_connection is defined and ansible_connection == "netconf")
  notify: 
    - iosxr_hostname
    
####################################################################
# Kick off handlers for unit testing                               #
####################################################################
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers