# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

####################################################################
# Classic IOS specific commands                                    #
####################################################################

- name: "IOS Global table loopback address"
  ios_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_lo0.j2"
  register: ioslo
  when: (ansible_network_os is defined and ansible_network_os == "ios" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - lo0

- name: "IOS No shut on global table loopback address"
  ios_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_lo0_no_shut.j2"
  when: ioslo.changed

####################################################################
# IOSXR specific commands                                          #
####################################################################

- name: "IOSXR Global table loopback address"
  iosxr_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_lo0.j2"
  register: iosxrlo
  when: (ansible_network_os is defined and ansible_network_os == "iosxr" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - xrlo0

- name: "IOSXR No shut on global table loopback address"
  iosxr_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_lo0_no_shut.j2"
  when: iosxrlo.changed

####################################################################
# NXOS specific commands                                           #
####################################################################

- name: "NX-OS Configure loopback"
  nxos_config:
    src: "{{ ansible_network_os }}_cli_lo0.j2"
  register: nxoslo
  when: (ansible_network_os is defined and ansible_network_os == "nxos" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - nxlo0

- name: "NXOS No shut on global table loopback address"
  nxos_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_lo0_no_shut.j2"
  when: nxoslo.changed


####################################################################
# IOSXR Netconf specific commands                                  #
####################################################################

- name: "NC create global table loopback address in no-shut state"
  netconf_config:
    src: "{{ ansible_network_os }}_nc_loopback.j2"
  when: (ansible_connection is defined and ansible_connection == "netconf")
#  notify: 
#    - nclo0
    
####################################################################
# Kick off handlers for unit testing                               #
####################################################################
    
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
