# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

####################################################################
# Classic IOS specific commands                                    #
####################################################################

- name: "IOS Global table loopback address"
  cisco.ios.ios_config:
    src: "ios_cli_lo0.j2"
  register: ioslo
  when: (ansible_network_os is defined and ansible_network_os == "cisco.ios.ios" and ansible_connection is defined and ansible_connection == "ansible.netcommon.network_cli")
#  notify: 
#    - ios_lo0

- name: "IOS No shut on global table loopback address"
  cisco.ios.ios_config:
    src: "ios_cli_lo0_no_shut.j2"
  when: ioslo.changed

####################################################################
# IOSXE specific commands                                          #
####################################################################

- name: "IOSXE NC create global table loopback address in no-shut state"
  ansible.netcommon.netconf_config:
    content: "{{ lookup('template', '../templates/iosxe_nc_loopback.j2') }}"
  when: (ansible_network_os is defined and ansible_network_os == "cisco.ios.iosxe" and ansible_connection is defined and ansible_connection == "netconf")
#  notify: 
#    - iosxe_lo0

####################################################################
# IOSXR specific commands                                          #
####################################################################

# IOSXR is managed through netconf

####################################################################
# NXOS specific commands                                           #
####################################################################

- name: "NX-OS Configure loopback"
  cisco.nxos.nxos_config:
    src: "{{ ansible_network_os }}_cli_lo0.j2"
    save_when: modified
  register: nxoslo
  when: (ansible_network_os is defined and ansible_network_os == "nxos" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - nxos_lo0

- name: "NXOS No shut on global table loopback address"
  cisco.nxos.nxos_config:
    src: "{{ ansible_network_os }}_cli_lo0_no_shut.j2"
    save_when: modified
  when: nxoslo.changed


####################################################################
# IOSXR Netconf specific commands                                  #
####################################################################

- name: "NC create global table loopback address in no-shut state"
  ansible.netcommon.netconf_config:
    content: "{{ lookup('template', '{{ ansible_network_os }}_nc_loopback.j2') }}"
  when: (ansible_network_os is defined and ansible_network_os == "iosxr" and ansible_connection is defined and ansible_connection == "netconf")
#  notify: 
#    - iosxr_lo0
    
####################################################################
# Kick off handlers for unit testing                               #
####################################################################
    
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
