# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

####################################################################
# Classic IOS specific commands                                    #
####################################################################

- name: "IOS Configure log servers"
  ios_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_log_servers.j2"
  with_items: "{{ logging }}"
  when: (ansible_network_os is defined and ansible_network_os == "ios" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - logging

- name: "IOS Configure logging"
  ios_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_logging.j2"
  when: (ansible_network_os is defined and ansible_network_os == "ios" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - ios_logging

####################################################################
# IOSXE specific commands                                          #
####################################################################

# IOSXE is managed through classic IOS or netconf

####################################################################
# IOSXR specific commands                                          #
####################################################################

# IOSXR is managed through netconf

####################################################################
# NXOS specific commands                                           #
####################################################################

- name: "NX-OS Configure log servers"
  nxos_config:
    src: "{{ ansible_network_os }}_cli_log_servers.j2"
    save_when: modified
  with_items: "{{ logging }}"
  when: (ansible_network_os is defined and ansible_network_os == "nxos" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - nxos_logging

- name: "NXOS Configure logging"
  nxos_config:
    src: "{{ ansible_network_os }}_cli_logging.j2"
  when: (ansible_network_os is defined and ansible_network_os == "iosxr" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - nxos_logging

####################################################################
# Netconf specific commands                                        #
####################################################################

- name: "Netconf configure logging"
  netconf_config:
    src: "{{ ansible_network_os }}_nc_logging.j2"
  when: (ansible_connection is defined and ansible_connection == "netconf")

- name: "Netconf configure log servers"
  netconf_config:
    src: "{{ ansible_network_os }}_nc_log_servers.j2"
  with_items: "{{ logging }}"
  when: (ansible_connection is defined and ansible_connection == "netconf")
#  notify: 
#    - nc_logging
    
####################################################################
# Kick off handlers for unit testing                               #
####################################################################
    
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
