# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

####################################################################
# Classic IOS specific commands                                    #
####################################################################

- name: "IOS Configure snmp"
  cisco.ios.ios_config:
    src: "ios_cli_snmp.j2"
  when: (ansible_network_os is defined and ansible_network_os == "cisco.ios.ios" and ansible_connection is defined and ansible_connection == "ansible.netcommon.network_cli")
#  notify: 
#    - ios_snmp

- name: "IOS Configure snmp servers"
  cisco.ios.ios_config:
    src: "ios_cli_snmp_servers.j2"
  when: (ansible_network_os is defined and ansible_network_os == "cisco.ios.ios" and ansible_connection is defined and ansible_connection == "ansible.netcommon.network_cli")
  with_items: "{{ snmp }}"
#  notify: 
#    - ios_snmp_servers

####################################################################
# IOSXE specific commands                                          #
####################################################################

# IOSXE is managed through classic IOS or netconf

####################################################################
# IOSXR specific commands                                          #
####################################################################

# IOSXR is managed through netconf

####################################################################
# NXOS specific commands                                           #
####################################################################

- name: "NXOS Configure snmp"
  cisco.nxos.nxos_config:
    src: "{{ ansible_network_os }}_cli_snmp.j2"
  when: (ansible_network_os is defined and ansible_network_os == "nxos" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - nxos_snmp

- name: "NX-OS Configure snmp servers"
  cisco.nxos.nxos_config:
    src: "{{ ansible_network_os }}_cli_snmp_servers.j2"
    save_when: modified
  when: (ansible_network_os is defined and ansible_network_os == "nxos" and ansible_connection is defined and ansible_connection == "network_cli")
  with_items: "{{ snmp }}"
#  notify: 
#    - nxos_snmp_servers

####################################################################
# Netconf specific commands                                        #
####################################################################

- name: "Netconf configure snmp"
  ansible.netcommon.netconf_config:
    content: "{{ lookup('template', '{{ ansible_network_os }}_nc_snmp.j2') }}"
  when: (ansible_network_os is defined and ansible_network_os == "iosxr" and ansible_connection is defined and ansible_connection == "netconf")
#  notify: 
#    - nc_snmp

- name: "Netconf configure snmp servers"
  ansible.netcommon.netconf_config:
    content: "{{ lookup('template', '{{ ansible_network_os }}_nc_snmp_servers.j2') }}"
    #timeout required because IOSXR tries to configure IPv6 host
    #timeout: 300
  when: (ansible_network_os is defined and ansible_network_os == "iosxr" and ansible_connection is defined and ansible_connection == "netconf")
  with_items: "{{ snmp }}"
#  notify: 
#    - nc_snmp_servers
    
####################################################################
# Kick off handlers for unit testing                               #
####################################################################
    
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
