# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

####################################################################
# Classic IOS specific commands                                    #
####################################################################

- name: "IOS Configure snmp servers"
  ios_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_snmp_servers.j2"
  with_items: "{{ snmp }}"
  when: (ansible_network_os is defined and ansible_network_os == "ios" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - snmp

- name: "IOS Configure snmp"
  ios_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_snmp.j2"
  when: (ansible_network_os is defined and ansible_network_os == "ios" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - ios_snmp

####################################################################
# IOSXR specific commands                                          #
####################################################################

- name: "IOSXR Configure snmp servers"
  iosxr_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_snmp_servers.j2"
  with_items: "{{ snmp }}"
  when: (ansible_network_os is defined and ansible_network_os == "iosxr" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - iosxr_snmp

- name: "IOSXR Configure snmp"
  iosxr_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_snmp.j2"
  when: (ansible_network_os is defined and ansible_network_os == "iosxr" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - iosxr_snmp

####################################################################
# NXOS specific commands                                           #
####################################################################

- name: "NX-OS Configure snmp servers"
  nxos_config:
    src: "{{ ansible_network_os }}_cli_snmp_servers.j2"
    save_when: modified
  when: (ansible_network_os is defined and ansible_network_os == "nxos" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - nxos_snmp

- name: "NXOS Configure snmp"
  nxos_config:
    src: "{{ ansible_network_os }}_cli_snmp.j2"
  when: (ansible_network_os is defined and ansible_network_os == "iosxr" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify: 
#    - nxos_snmp

####################################################################
# Netconf specific commands                                        #
####################################################################

- name: "Netconf configure snmp"
  netconf_config:
    src: "{{ ansible_network_os }}_nc_snmp.j2"
  when: (ansible_connection is defined and ansible_connection == "netconf")
#  notify: 
#    - nc_snmp

- name: "Netconf configure snmp servers"
  netconf_config:
    src: "{{ ansible_network_os }}_nc_snmp_servers.j2"
  when: (ansible_connection is defined and ansible_connection == "netconf")
#  notify: 
#    - nc_snmp
    
####################################################################
# Kick off handlers for unit testing                               #
####################################################################
    
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
