# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

####################################################################
# Netconf specific commands                                        #
####################################################################

- name: "NC Set clock and timezone"
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ creds['username'] }}"
    password: "{{ creds['password'] }}"
    src: "{{ netconf }}_nc_clock.j2"
  when: netconf is defined
  notify: 
    - time

- name: "NC Set summertime"
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ creds['username'] }}"
    password: "{{ creds['password'] }}"
    src: "{{ netconf }}_nc_summertime.j2"
  when: netconf is defined
  notify: 
    - time

- name: "NC Configure ntp"
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ creds['username'] }}"
    password: "{{ creds['password'] }}"
    src: "{{ netconf }}_nc_ntp.j2"
  when: netconf is defined
  notify: 
    - time

- name: "NC Configure ntp key"
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ creds['username'] }}"
    password: "{{ creds['password'] }}"
    src: "{{ netconf }}_nc_ntpkey.j2"
  when: netconf is defined
  notify: 
    - time

####################################################################
# Classic IOS specific commands                                    #
####################################################################

- name: "IOS Set clock and timezone"
  ios_config:
    provider: "{{ provider }}"
    authorize: yes
    src: "time_timezone_ios.j2"
  when:  (cli is defined and cli == "ios")
  notify:
    - time

- name: "IOS Set summertime"
  ios_config:
    provider: "{{ provider }}"
    authorize: yes
    lines:
      - clock summer-time {{ timezone }} recurring last Sun Mar 2:00 last Sun Oct 3:00
  when:  (cli is defined and cli == "ios")
  notify:
    - time

- name: "IOS Configure ntp"
  ios_config:
    provider: "{{ provider }}"
    authorize: yes
    src: "time_ntp_ios.j2"
  when:  (cli is defined and cli == "ios")
  notify:
    - time

- name: "IOS Configure ntp key"
  ios_config:
    provider: "{{ provider }}"
    authorize: yes
    lines:
      - ntp authentication-key {{ ntp_key_id }} md5 {{ ntp_key }} 
  when:  (cli is defined and cli == "ios")
  notify:
    - time
    
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
