# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

####################################################################
# Classic IOS specific commands                                    #
####################################################################

- name: "IOS Set timezone"
  ios_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_clock_timezone.j2"
  when: (ansible_network_os is defined and ansible_network_os == "ios" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify:
#    - ios_time

- name: "IOS Set summertime"
  ios_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_clock_summertime.j2"
  when: (ansible_network_os is defined and ansible_network_os == "ios" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify:
#    - ios_time

- name: "IOS Configure ntp key"
  ios_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_ntp_key.j2"
  when: (ansible_network_os is defined and ansible_network_os == "ios" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify:
#    - ios_time

- name: "IOS Configure ntp"
  ios_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_ntp.j2"
  when: (ansible_network_os is defined and ansible_network_os == "ios" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify:
#    - ios_time

- name: "IOS Configure ntp servers"
  ios_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_ntp_servers.j2"
  with_items: "{{ ntp }}"
  when: (ansible_network_os is defined and ansible_network_os == "ios" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify:
#    - ios_time

####################################################################
# IOSXE specific commands                                          #
####################################################################

# IOSXE is managed through classic IOS or netconf

####################################################################
# IOSXR specific commands                                          #
####################################################################

# IOSXR is managed through netconf

####################################################################
# NXOS specific commands                                           #
####################################################################

- name: "nxos Set timezone"
  nxos_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_clock_timezone.j2"
  when: (ansible_network_os is defined and ansible_network_os == "nxos" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify:
#    - nxos_time

- name: "nxos Set summertime"
  nxos_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_clock_summertime.j2"
  when: (ansible_network_os is defined and ansible_network_os == "nxos" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify:
#    - nxos_time

- name: "nxos Configure ntp key"
  nxos_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_ntp_key.j2"
  when: (ansible_network_os is defined and ansible_network_os == "nxos" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify:
#    - nxos_time

- name: "nxos Configure ntp"
  nxos_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_ntp.j2"
  when: (ansible_network_os is defined and ansible_network_os == "nxos" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify:
#    - nxos_time

- name: "nxos Configure ntp servers"
  nxos_config:
    authorize: yes
    src: "{{ ansible_network_os }}_cli_ntp_servers.j2"
  with_items: "{{ ntp }}"
  when: (ansible_network_os is defined and ansible_network_os == "iosnxosxr" and ansible_connection is defined and ansible_connection == "network_cli")
#  notify:
#    - nxos_time

####################################################################
# Netconf specific commands                                        #
####################################################################

- name: "NC Set clock and timezone"
  netconf_config:
    src: "{{ ansible_network_os }}_nc_clock_timezone.j2"
  when: (ansible_connection is defined and ansible_connection == "netconf")
#  notify: 
#    - nc_time

- name: "NC Set summertime"
  netconf_config:
    src: "{{ ansible_network_os }}_nc_clock_summertime.j2"
  when: (ansible_connection is defined and ansible_connection == "netconf")
#  notify: 
#    - nc_time

- name: "NC Configure ntp"
  netconf_config:
    src: "{{ ansible_network_os }}_nc_ntp.j2"
  when: (ansible_connection is defined and ansible_connection == "netconf")
#  notify: 
#    - nc_time

- name: "NC Configure ntp key"
  netconf_config:
    src: "{{ ansible_network_os }}_nc_ntp_key.j2"
  when: (ansible_connection is defined and ansible_connection == "netconf")
#  notify: 
#    - nc_time

- name: "NC Configure ntp servers"
  netconf_config:
    src: "{{ ansible_network_os }}_nc_ntp_servers.j2"
  with_items: "{{ ntp }}"
  when: (ansible_connection is defined and ansible_connection == "netconf")
#  notify: 
#    - nc_time
    
####################################################################
# Kick off handlers for unit testing                               #
####################################################################
    
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
